use_default_settings: true

server:
  bind_address: "0.0.0.0"
  port: 8080
  secret_key: "gamerovers-local-development-key-change-before-public-deployment"
  limiter: false
  image_proxy: false

search:
  safe_search: 0
  default_lang: "all"
  formats:
    - html
    - json

outgoing:
  request_timeout: 4.0
  max_request_timeout: 8.0
  pool_connections: 50
  pool_maxsize: 20
